/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { Iminion } from "./Iminion";

export class IminionFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Iminion {
    return new Contract(address, _abi, signerOrProvider) as Iminion;
  }
}

const _abi = [
  {
    inputs: [],
    name: "moloch",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];
